examples/astar-path-finding.rs
examples/dijkstra-path-finding.rs
src/lib.rs
tcod-sys/lib.rs

Some syntax changed during the most recent nightly releases, and some traits were removed from the prelude. Iterator definitions also changed to use associated types.

Various changes to fix building on latest nightly

---

README.md

Note: this fails only because the current build fails. Fixed in #61

Add build status to the README

---

README.md

Some of the links in the README weren't working, so I've converted them back to the \[text](link) syntax so that they're picked up as links.
I also changed it to use fenced code blocks since a couple of the code blocks weren't being registered as code, and just showed up as plain text.

Miscellaneous README clean-up

---

src/lib.rs

I'm not sure what's the convention for porting names from the C API to Rust, so I pretty much kept them the same.
`sys_check_for_event()` is a bit messy internally, I think it should delegate much of its behavior to `KeyState` and `MouseState`.
I'm not too happy about the way it's used currently either. It doesn't feel like you're using a high level langage and requires to setup one or two mutable variables. I wasn't sure what to do so this is a direct port from the C API.
Here is an example of how I use it currently:
let mut mouse_state = tcod::MouseState::new();
let mut key_state = tcod::KeyState::new();
loop {
let event = tcod::sys_check_for_event(
tcod::KEY | tcod::MOUSE,
Option::Some(&mut key_state),
Option::Some(&mut mouse_state));
if !(event & tcod::KEY).is_empty() {
println!("{}", …

Added mouse support (mouse_show_cursor(), mouse_is_cursor_visible(), mouse_move() and sys_check_for_event())

---

src/lib.rs

First batch of mouse improvements.
* `sys_check_for_event()` now returns `(EventFlags, Event)` where `Event` is:
enum Event {
Key(KeyState),
Mouse(MouseState),
None
}
*  `sys_check_for_event()` moved to  `system::check_for_event()` (I also put `Event` in `system`, feel free to chang this).
While writing this, I was wondering if `mouse_*` functions should be moved to a `mouse` module?
Usage example:
loop {
let (flags, event) = tcod::system::check_for_event(
tcod::KEY | tcod::MOUSE);
match event {
tcod::system::Event::Key(ref key_state) => {
// ...
},
tcod::system::Event::Mouse(ref mouse_state) => {
// ...
}
tcod::system::Event::None => {
break;
}
}
}

Mouse support improvements

---

Cargo.toml
src/lib.rs

The bitflags! macro was moved out of Rust and onto crates.io, so this adds it as a dependency.

Update to work with the latest version of Rust

---

src/lib.rs

I wrongly named `FOV_RESTRICTIVE` as `Permissive9` on my previous PR. This fixes that.

Fix Restrictive FOV algorithm.

---

src/lib.rs
tcod-sys/build.rs
tcod-sys/lib.rs

`unstable` lint was replaced with a more fine-grained feature opt-in system.
Let's just opt in to everything we use for now.

Silence the new warnings

---

tcod-sys/build.rs

`os::getenv` was recently deprecated. Changed to use the new `env` library instead - environment variables are retrieved using `env::var` or in this case `env::var_string`.

Remove deprecated method of getting environment variables

---

.travis.yml

Yesterday I tried compiling my roguelike on OS X and got an error. This just makes sure that the library is tested on both platforms.

Test on both Linux and OSX

---

.travis.yml

Reverts tomassedovic/tcod-rs#98 since the build script is not prepared to test on OSX (for example, we cannot use `apt-get` on OSX to get dependencies).

Revert "Test on both Linux and OSX"

---

examples/astar-path-finding.rs
examples/dijkstra-path-finding.rs
examples/fov.rs

It no longer exists and using it causes warnings on `cargo test`.

Remove `feature(core)`

---

src/lib.rs
tcod-sys/build.rs
tcod-sys/lib.rs

This fixes a handful of warnings and errors on the latest Rust:
rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)

Update to latest Rust

---

.travis.yml
README.md

upx and electric-fence are libtcod dev dependencies, not something need for
production.

Don't show the unnecessary linux dependencies

---

examples/chars.rs

The chars module added a bunch of extended characters we can draw. This
adds an example which uses some of them.
(example for #111)

Add example for chars::*

---

Cargo.toml

The referenced issue isn't closed, but we're no longer getting build
errors so let's do this.

Add the debug symbols back for debug/test builds

---

src/lib.rs
tcod-sys/build.rs

Seeing as Cargo and various other prominent projects have begun the migration onto the new IO and Path libraries, it seems like a good time for us to do the same.
I was as careful as I could be, but it'd be great if you could have a quick look over.
This is also a breaking change for our users - our public API takes old_path::Path objects so users will need to migrate onto the newer path API also.

Move tcod-rs from std::{old_io, old_path} -> std::{io, path}

---

examples/mouse.rs
src/lib.rs

It's used like this:
```
for (flags, event) in tcod::system::check_for_event_iter() {
match event {
IteratedEvent::Key(ref key_state) => {
// ...
},
IteratedEvent::Mouse(ref mouse_state) => {
// ...
}
}
}
```

Added iterator version of tcod::system::check_for_event()

---

tcod_sys/build.rs

This fixes the current issue with `cargo test`.

Switch to the new syntax for linking in tcod_sys build script

---

examples/fov.rs
src/lib.rs
tcod_sys/lib.rs

rust-bindgen has not been updated yet, and the manual fix is fairly staightforward. In the two cases where adding the appropriate Clone attribute wasn't enough:
1. the generated LLVM IR seems to be fine for struct containing actual data (it calls memcpy on both arrays). (tcod_sys/lib.rs:486)
2. copying function pointers should be fine. (tcod_sys/lib.rs:626)
Also, all the provided examples work fine, but I don't have a bigger project to test it on right now.

Manually fixed Copy and Clone generation

---

examples/blit.rs
examples/chars.rs
examples/colors.rs
examples/fov.rs
examples/keyboard.rs
examples/minimal.rs
examples/mouse.rs
examples/text.rs
src/console.rs
src/lib.rs

This still has the names `OffscreenConsole` and `RootConsole`. I'm kind of partial to these, since you can import them nicely from the `console` module and still know what they do.
If the naming is fine as it is, then this closes #137

Console API rework

---

tcod_sys/build.rs

Really simple fix, changes "static" to "dylib" though, not sure why it was static because when I tried the output was a DLL.

Update tcod_sys build to work on paths with spaces

---

src/pathfinding.rs

Rust allows the implementation of the Drop trait for structs with lifetime parameters, so this current solution is equivalent to the previous one.

Removed redundant native type wrappers.

---

src/bindings.rs
src/colors.rs
src/console.rs
src/lib.rs

The blocking of the Root initializer with phantom types (mentioned in #144) was indeed the right idea. The way it is implemeted now generates no extra assembly (which is to be expected from `PhantomData`) but still blocks explicit instantiation of `Root` consoles.
The second part of this PR is making the API of the `Color` struct consistent with that of `Map's`. Since the `AsNative` trait was already approved, I implemented that on `Color` instead of a method directly on he struct. The `FromNative` trait is a natural addition that matches the style of `AsNative` quite nicely. 
This has the following advantages:
* no more potentially unsafe operations exposed as safe (in `Color`'s case `TCOD_color_t` was safe anyway, but it's better to be safe than sorry).
* consisteny between modules: if …

Root creation blocking and consistency

---

examples/blit.rs
src/console.rs

Closes #148, since this seems to be the more sensible solution to the problem. Adding a macro for rarely used functionality seems like a bit of an overkill.

Group related blit arguments into tuples

---

examples/print_macros.rs
src/console.rs
src/console_macros.rs
src/lib.rs

I'm not too attached to the macros part, I pretty much just wanted to get a second opinion, and I thought I would put it in the PR. I think it's nicer to use then the miriad of printing functions in `libtcod` and it also has the advantage of accepting Rust-style format strings. 
The thing I dislike about it is that the printing modifiers come before the string we want to print. Because of the macro definition rules there's only one solution to this problem: wrapping the `$($arg: tt)*` part in some kind of parentheses, which is also not ideal.
I'll do [these](http://doryen.eptalys.net/data/libtcod/doc/1.5.2/html2/console_advanced.html) next, any ideas for a nice API? I'm thinking enums with variants that take `i32`'s as their parameters and a single `Console::draw` method. The problem with …

Started implementing missing features

---

examples/roguelike-tutorial-1.rs
examples/roguelike-tutorial-2.rs
src/console.rs
src/system.rs

This let's us pass a str and Path to `RootInitializer::font` for example.
We get back the ergonomics of accepting `&str`, but if a user has a Path, they
can still just pass it in.
The situation here is complicated by the fact that we have to store the value in
the `RootInitializer` struct, which can be done either by taking a Reference to
`AsPath` or by saving it in a Box.
I've opted for the latter since the struct is short-lived and it will only be
done once. Otherwise, we'd have to put the str and Path behind an reference:
Root::initializer().font("terminal.png").init();
vs.
Root::initializer().font(&"terminal.png").init();

Use `AsRef<Path>` for fns that take a fs path

---

examples/shapes.rs
src/console.rs

This implements libtcod's rect, hline, vline and print_frame functions and adds
an example showing how to use them.

Add methods for drawing shapes

---

src/bindings.rs
src/console.rs
src/console_macros.rs
src/system.rs

Implementation as per #161 and #162
As far as I could tell everything works fine. The example mentioned in #161 (printing `b"90\xf8"`) also works correctly, provided we use the Unicode equivalent of the special character: `"90\u{f8}"`. It also seems like there is no need to implement separate printing for single characters: `TCOD_console_put_char_xx` and `TCOD_console_set_char` already take `i32` as their arguments, which `char` can be easily casted to (as it is done now).

Unicode printing and AsRef consistency

---

examples/text.rs
src/console.rs

I wrote a detailed summary of my opinions in #161, but here's a possible implementation for the ASCII literal printing. This actually works quite well, and as soon as Rust has negative trait bounds we can implement `TcodString` for `AsRef<str>` as well. The obvious limitation is the hard coded limit on the fixed size arrays, but note that even the standard library only implements traits for fixed-sized arrays up to  the [size 32](https://doc.rust-lang.org/nightly/core/primitive.array.html).
Other than that I think this works as most users would expect: ASCII literals in Rust guarantee that for each character a single byte is passed (with a value of 0-255) which is what `libtcod` expects. In the case of regular strings the UTF conversion occurs if the given string had a character that was …

Support for proper printing of ASCII literals

---

examples/text.rs
src/console.rs

This can only be used with ASCII strings, unfortunately.

Add `Console::get_height_rect`

---

src/console.rs

This is now identical to print_rect and print_rect_ex, so it won't crash on the
former if it worked on the latter.
Libtcod seems to be clipping things correctly and valgrind didn't register any
invalid access.

Relax the assert in get_height_rect

---

.gitignore
Cargo.toml
examples/namegen.rs
examples/names.txt
src/bindings.rs
src/console.rs
src/input.rs
src/lib.rs
src/namegen.rs
src/random.rs
src/system.rs
tcod_sys/Cargo.toml

Name generation functionality, but I had to wrap to whole pseudorandom-generator module as well (namegen, noise requires this). The name generator has a very obvious limitation: you can only ever have one name generator at any given time. I have no idea how to wrap a global construct more elegantly, but we do need a separate structure to remain memory safe: `libtcod` would happily use random number generators that have already been freed (hence the stored copies in `Namegen`).
If there are any alternative API ideas, I'd be happy to hear them.

Name Generator

---

src/image.rs
src/lib.rs

Safe wrapper for `libtcod's` [image toolkit](http://roguecentral.org/doryen/data/libtcod/doc/1.5.2/html2/image.html). I left a few TODOs in the code, if you think they can be ignored I'll resubmit the PR without them, but I think they're worth considering. I'll comment on the appropriate lines with a little bit of further information.

Image toolkit

---

src/system.rs

Libtcod documentation states of `TCOD_sys_set_fps`: "Maximum number of frames per second. 0 means unlimited frame rate."

Zero is a valid value to pass to TCOD_sys_set_fps

---

tcod_sys/libtcod/src/path_c.c

Sorry about this, the `libtcod` lists don't actually own the data they contain, so deleting the list instead of clearing (the original, buggy behavior) is enough.

Small fix for memory leak patch

---

src/console.rs

In `print_frame` the assertion is off by one.
In `blit` negative destination is perfectly fine.

Two overly cautious asserts

---

examples/keyboard.rs
examples/roguelike-tutorial-1.rs
examples/roguelike-tutorial-2.rs
examples/samples.rs
src/console.rs
src/input.rs

This fixes #184 because of which we couldn't access certain keys. The `KeyState` struct is renamed to `Key` and has fields `code` and `printable` that correspond to libtcod's `vk` and `c`.
This also adds two convenience fields: `alt` and `ctrl` that are true if the left or right variant is pressed.
This is a breaking change. To update your code, convert it to match on the `Key` struct. I.e. replace this:
```rust
match keypress.key {
Special(Enter) if keypress.left_alt => { // fullscreen }
Special(Escape) => { // exit game }
Key::Printable('>') => { // descend }
}
```
with this:
```rust
match keypress {
Key { code: Enter, alt: true, .. } => { // fullscreen }
Key { code: Escape, .. } => { // exit game }
Key { printable: '>', .. } => { // descend }
}
```

Key reform

---

src/namegen.rs

libtcod doesn't have a "namegen new" function. We use `Namegen::new()`
to ensure memory safety. But we cannot call `TCOD_namegen_destroy`
unless we've actually called parse first. We get a segfault otherwise:
```rust
extern crate tcod;
use tcod::namegen::Namegen;
fn main() {
let namegen = Namegen::new();
}
```
Fixes #189.

Fix segfault on an unparsed namegen

---

README.md

I forgot to add line toolkit to project's README.

Updated README to list line toolkit as implemented

---

Cargo.toml
examples/samples.rs
src/system.rs

`std::time::Duration` is stable as of Rust 1.3. Using it simplifies our
dependencies and should make interoperability with other code easier.
There is a couple of downsides:
First, the API of the Duration in std is smaller than the one in the
time crate so we need to e.g. do our own conversion to total seconds and
milliseconds elapsed. I'm hoping this will get better in the future or
will be something the time crate will adopt while using
std::time::Duration for the underlying data.
Second, this is a breaking change because it no longer works with the
older (<=1.2) compilers.

Replace external `Time` crate with `std::time`

---

src/input.rs
src/namegen.rs

Non-breaking change with small fixes: 
1. Use `is_empty` instead of `len() > 0`
2. Implement `From` instead of `Into` for `Key`. The reason: `Into` is blanket implemented for everything that implements `From`, so we get an extra trait for no cost.

Small fixes

---

tcod_sys/Cargo.toml

It should never have been included in the first place and Cargo seems to
be ignoring the .gitignore file.
Fixes #165.

Exclude zlib.a from the package

---

Makefile

It will package both tcod and tcod_sys, making sure none of the
generated files (*.a, etc.) are included.

Add a `make package` command

---

tcod_sys/build.rs

Here's a basic workaround for the crater builds. A few things:
- Should I check for every enviromental variable, or do you think think `CRATER_TASK_TYPE` is enough? 
- This has the annoying property that the user has to manually do a `cargo clean` betwen a crater and a non-crater build. I don't think this is too much of a downside, but I have no idea how to fix it
Closes #210

Fix for crater builds

---

src/console.rs

We're getting a warning for E0446 in the recent builds. Making this
trait public fixes it.

Make the AsciiLiteral trait public

---

Cargo.toml
tcod_sys/Cargo.toml

Older versions of libc no longer compile on latest Rust (1.7 stable at
the moment)[1][2]. This updates our required dependency version to
0.1.12, but it seems that this alone will not rebuild Cargo.lock if it
has an incompatible libc.
Fixes #216
[1]: https://github.com/rust-lang-deprecated/time/issues/84
[2]: https://github.com/tomassedovic/tcod-rs/issues/216

Update libc version

---

src/map.rs

We were only checking that the x and y were greater or equal to zero,
but they must also be lower than the map's width and height.
Discovered this when my roguelike crashed because of this (assert within
libtcod itself).

Add missing asserts in the FOV map functions

---

src/bindings.rs

Exporting extern crates without marking them public will be phased out
in future versions of the compiler, see
https://github.com/rust-lang/rust/pull/31362
This was caught in a crater run by the core team here:
https://gist.github.com/alexcrichton/78cf7d4740391546e2d5

Explicitly re-export tcod_sys (ffi)

---

tcod_sys/build.rs

This should fix the issue #222 according to the following build run:
https://ci.appveyor.com/project/tomassedovic/tcod-window/build/1.0.5
Looks like MinGW expects to get just the dynamic library's name without
the suffix.

Remove the '.dll' suffix from windows-gnu target

---

src/console.rs

Useful counterpart to the `set_default_background` method.

Add Console::get_default_background

---

src/console.rs

The upstream docs are wrong on this one: `x + width` can be equal to the
console's width as well. It would be impossible to have a rect that ends
at the right edge of the console. And the same goes for height.
In addition, I've split the conditions each into its own assert. When it
fires, it's useful to know which condition in particular failed (was it
the `x` or the `y` check?). This generates much more useful error
messages.

Fix the with and height asserts in Console::rect

---

README.md

As evidenced in issue #232, pkg-config might not be installed on a Mac,
but we need it for the tcod-sys build script.

Add pkg-config as an OSX prerequisite

---

tcod_sys/Cargo.toml
tcod_sys/build.rs

`gcc` was renamed to `cc` and is now 1.0 \o/.

Switch from the gcc to cc crate

---

src/console.rs

I was trying to draw a horizontal line across the entire width of a console when I ran into this.

Fix line length assert

---

examples/samples.rs

The example doesn't need direct access to this crate.

examples: Remove usused `crate tcod_sys`

---

README.md

This was updated in #256, since then https://github.com/tomassedovic/tcod-rs/blob/master/tcod_sys/libtcod/README.md mentions 1.6.3, however the README.md incorrectly still mentioned 1.5.2.
(the project description on github also does)

README.md: mention that version 1.6.3 is wrapped

---

README.md
tcod_sys/Cargo.toml
tcod_sys/build.rs

Build static library for libtcod on Linux
Tell rust to link the static version of libtcod on Linux.
This avoids issues about where to put `libtcod.so` at run time by including the code in the executable itself.
This is my attempt at #262. I think the same should work for other operating systems but I am unable to test this right now.

Build static library for libtcod on Linux

---

README.md

v0.13 seems to require SDL2 instead of SDL1.2.

Update version of the SDL dev bindings required

---

src/console.rs

Marked Offscreen as Send, this is probably not actually safe because libtcod is not threadsafe, but so far I've not found any problems.  In the meantime this would allow Offscreen consoles to be used as resources in specs (like the Root console).

Added Send to Offscreen

---

.travis.yml

Stable is always required to pass, nightly is optional on both Linux
and macOS.

Update the CI whitelist

---

src/colors.rs

Makes it so that it's possible to write
```rust
const LINK_COLOR: Color = Color::new(0x00, 0xCC, 0x00);
```
Saves the user from using the struct directly.

make Color::new a const function

---

tcod_sys/build.rs

The recent build failures seem to have been introduced in rust 1.35, because the compiler handles redundant linker flags differently.
It is now important to have the last occurrence of `-lSDL2` after the last occurrence of `-ltcod`
i am not sure if this is the right fix, but it seems to get everything going again and should resolve #288

Fix build on linux

---

README.md

realized the README is wrong about the crate-name while investigating the recent build failures.
it should now be copy-and-pasteable and just work

Fix documentation of building tcod-sys as dynamic lib

---

src/map.rs

This change adds an implementation of Clone for the Map type using the TCOD_map_copy function from tcod.
This addresses issue #284

Add 'impl Clone' for Map using libtcod ffi function

---

src/map.rs

In the vein of #274, this is basically a lighter version of #265 until #259 is "properly" resolved. (User code will still need to `Arc<Mutex<Map>>`, which I think is an OK trade-off at this point)
Use-case: using Specs, I want to be a good little boy-scout, and have a dedicated `FovSystem` update a `Map` resource that is then read by the `RenderSystem`.

Added Send to Map

---

tcod_sys/libtcod/src/sys_sdl2_c.c

Related to https://github.com/tomassedovic/tcod-rs/issues/267
Basically, SDL2 on OS X requires you to `SDL_PumpEvents()` before setting the window size, otherwise you get a blank screen until it receives an event, such as a keyboard event or window resize event.
See also: https://discourse.libsdl.org/t/macos-10-14-mojave-issues/25060

Fix SDL2 rendering in Mojave

---

examples/blit.rs
examples/samples.rs
src/bsp.rs
src/console.rs
src/pathfinding.rs

the new `dyn` syntax for trait-objects is available since rust 1.27
rust-nightly has started warning that the old syntax is deprecated.
https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

fix bare trait object warnings on rust-nightly

---

README.md

The project has moved to github in the meantime, fix this.

Fix libtcod link in Readme

---

src/input.rs

Replaced uninitialised calls with MaybeUninit.

Fixed uninitialized error in `check_for_events`
