- src/lib.rs
> Update for the current Rust Alpha

- examples/astar-path-finding.rs
- examples/dijkstra-path-finding.rs
- examples/minimal.rs
- src/lib.rs
- tcod-sys/lib.rs
Works with `rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)`
> Update to rust master

- examples/astar-path-finding.rs
- examples/dijkstra-path-finding.rs
- src/lib.rs
> Convert isize to i32

- src/lib.rs
Adds `Map::compute_fov` and `Map::is_in_fov` for calculating FOV.
I wasn't sure how to implement the different fov_algorithms, I hope this way is fine, I just did it as colors is done.
Please review~
> Add FOV functions.

- tcod-sys/build.rs
In accordance with [this commit](https://github.com/rust-lang/rust/commit/a828e7948069f310dc5b33be8edb65e5e8e0cf9a).
> Change var_string -> var in tcod-sys/build.rs

- .travis.yml
> Use a new Github API key for the documentation

- .travis.yml
> Add new travis token

- src/lib.rs
This is not complete, but it covers most of the missing stuff (complements to
get/set pairs, fullscreen, etc.)
> Add a bunch of missing console functions

- tcod-sys/Cargo.lock
> Correct tcod-sys version in its Cargo.lock

- .gitignore
- tcod-sys/Cargo.lock
> Remove lock files

- tcod-sys/build.rs
> Remove unnecessary 'process' feature gate

- src/lib.rs
This silences the new warnings introduced in the latest nightly.
> Remove unnecessary casts

- Cargo.toml
This fixes the failures with latest Rust.
> Update rand dependency to 0.3.5

- Cargo.toml
- src/lib.rs
- tcod_sys/Cargo.toml
> Make compatible with rustc 1.0.0-beta

- Cargo.toml
- README.md
> Add missing contributors

- src/bindings.rs
- src/colors.rs
- src/console.rs
- src/map.rs
This is a more limiting solution than the previous one, but I don't really see a better way of getting around the problem.
> Fix for the unconstrained lifetime

- .travis.yml
These are just simple bindings so 1.0.0 should be fine (that's what most
new people will be starting with I assume) and it'd be good to see when
the nightly breaks.
> Have Travis test 1.0.0 and Nightly

- examples/colors.rs
- src/colors.rs
Here's the PR for #172. I converted `lerp` to a free function, if you don't like it I'll resubmit without it (I still think it reads better). Also added division for for the operators. As a question: should I just add `Index` and `IndexMut` as well?
> Color operators and lerp as free function

- .travis.yml
- Cargo.toml
- Makefile
- src/colors.rs
- src/input.rs
- src/lib.rs
Where it makes sense: Default for Color, KeyState and MouseState. RustcEncodable/Decodable for Color.
> Add Default, RustcEncodable and RustcDecodable traits

- tcod_sys/libtcod/src/path_c.c
Upstream patch by @Gustorn that fixes the memory leaks in Dijkstra path finding. \o/
> Memory leak fix

- tcod_sys/libtcod/src/path_c.c
Fixed the uninitialized acces in Dijkstra pathfinding.
> Libtcod Fixes

- src/pathfinding.rs
We don't have to cast the callback closure to a trait object and
therefore store its fat pointer and pass that as libtcod's user data. By
making `c_path_callback` generic over the closure, we can pass the
pointer to the closure as user data directly.
This saves us an extra indirection, makes the code simpler and gets rid
of `mem::transmute`.
I've tested this on the examples and ran them through valgrind. Astar is
clean as before, Dijkstra is showing memory issues, but again, that's
same as before.
> Simplify the unsafe callback code in path finding

- src/pathfinding.rs
- src/system.rs
Implemented non-destructive path iterators, these should make displaying paths more convenient.
> Reference path iterator

- README.md
- examples/samples.rs
- src/lib.rs
- src/noise.rs
> Wrapper around Noise

- README.md
- examples/samples.rs
- src/bsp.rs
- src/lib.rs
- tcod_sys/lib.rs
BSP toolkit and related example.
> BSP toolkit

- src/console.rs
rust-lang/rust#28811
For the future: can I merge bugfixes like this without your review @tomassedovic?
Fixes #205
> Fix for breaking change in libstd

- appveyor.yml
It uses appveyor.com and should provide msvc and mingw coverage on 32
and 64 bit machines.
> Add Windows CI

- src/map.rs
Adds binding to `TCOD_map_clear` function.
> Add Map::clear function

- tcod_sys/build.rs
I'm not 100% sure what the underlying issue was, but there have been
warnings from the Visual Studio compiler and linker about our generated
`*.o` and `*.a` files and how we were including them and I think they
may have ended up being ignored.
So I've changed the MSVC branch to pass the C files to the final
compiler directly and just build everything in one command. This, in
addition to some compile switches to make it work seems to do the trick.
Fixes #234 hopefully.
> Fix MSVC targets

- src/console.rs
Calling `CString::new(..).unwrap().as_ptr()` creates a dangling pointer
because the `CString` gets dropped after the `unwrap` call.
So we now bind it into a local variable and call `as_ptr` in a separate
step which ensures the `CString` doesn't get dropped too early.
Fixes #240
> Fix the memory safety issue with print_frame

- tcod_sys/build.rs
Quick patch to match new gcc-rs API.
> Updating tcod-sys build.rs file to match new gcc-rs api.

- src/console.rs
https://github.com/tomassedovic/tcod-rs/issues/295
> Add get_default_foreground to src/console.rs
